### PR TITLE
replacing string with float 

### PR DESCRIPTION
**Pull request by brittosandro**

### CODE REVIEW

**Comment by hmcezar** [comment]
Could you provide a description of the changes and why do you think they are needed?
Writing the values to files instead of printing to STDOUT seems like a bad decision to me, since it will raise problems when there are existing files when you could just redirect the output to a file using `> file.dat`.

And the changes to `plot_en_angle_gaussian_scan.py`, why are they needed? Was your Gaussian `.log` obtained from the input generated with `plot_eff_tors.py`?

**Comment by brittosandro** [comment]
I shouldn't have suggested these changes. The only change I seem to need is the correction of the plot_en_angle_gaussian_scan.py file, as the script was getting a string value.

**Comment by hmcezar** [comment]
No problem.

In this case, could you please revert the commits with the other changes, and keep just the one that fixes the string to float conversion?

**Comment by brittosandro** [comment]
Unnecessary commits reversed.

**Comment by hmcezar** [comment]
I think you reversed the commits on a local branch or did not push the changes. I can't see the changes here.

**Comment by brittosandro** [comment]
I believe it worked now.

**Review by hmcezar — APPROVED** [review]

**Review by hmcezar — APPROVED** [review]

**Review by hmcezar — APPROVED** [review]

**Review by hmcezar — APPROVED** [review]

**Review by hmcezar — APPROVED** [review]

**Review by hmcezar — APPROVED** [review]

**Pull request merged**
